      - run: pip install requests

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: posted.json
          key: spotify-release-state

      - run: python main.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: posted.json
          key: spotify-release-state
